"""add raw_text column for jobs

Revision ID: 3008d9e565df
Revises: 7b3ba1c5718d
Create Date: 2026-04-29 14:33:59.014322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3008d9e565df'
down_revision: Union[str, Sequence[str], None] = '7b3ba1c5718d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('raw_text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'raw_text')
    # ### end Alembic commands ###
