"""add job table with normalized snake_case columns

Revision ID: 7b3ba1c5718d
Revises: 6a3a1222ed10
Create Date: 2026-04-28 18:58:02.489712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b3ba1c5718d'
down_revision: Union[str, Sequence[str], None] = '6a3a1222ed10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_content', sa.String(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('share_link', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('advertiser', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_origin_id'), 'jobs', ['origin_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_origin_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
